# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: C:/Users/shinderink/REC/snake/VivadoVideoProcessing/VideoOut/VideoOut.srcs/sources_1/bd/TopDesign/ip/TopDesign_v_tc_0/TopDesign_v_tc_0.xci
# IP: The module: 'TopDesign_v_tc_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Users/shinderink/REC/snake/VivadoVideoProcessing/VideoOut/VideoOut.srcs/sources_1/bd/TopDesign/ip/TopDesign_v_tc_0/TopDesign_v_tc_0_clocks.xdc
# XDC: The top module name and the constraint reference have the same name: 'TopDesign_v_tc_0'. Do not add the DONT_TOUCH constraint.
set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet

# XDC: c:/Users/shinderink/REC/snake/VivadoVideoProcessing/VideoOut/VideoOut.srcs/sources_1/bd/TopDesign/ip/TopDesign_v_tc_0/TopDesign_v_tc_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'TopDesign_v_tc_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet

# IP: C:/Users/shinderink/REC/snake/VivadoVideoProcessing/VideoOut/VideoOut.srcs/sources_1/bd/TopDesign/ip/TopDesign_v_tc_0/TopDesign_v_tc_0.xci
# IP: The module: 'TopDesign_v_tc_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Users/shinderink/REC/snake/VivadoVideoProcessing/VideoOut/VideoOut.srcs/sources_1/bd/TopDesign/ip/TopDesign_v_tc_0/TopDesign_v_tc_0_clocks.xdc
# XDC: The top module name and the constraint reference have the same name: 'TopDesign_v_tc_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet

# XDC: c:/Users/shinderink/REC/snake/VivadoVideoProcessing/VideoOut/VideoOut.srcs/sources_1/bd/TopDesign/ip/TopDesign_v_tc_0/TopDesign_v_tc_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'TopDesign_v_tc_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet
