# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# XDC: imports/src/pynq-z2_v1.0.xdc

# Block Designs: bd/TopDesign/TopDesign.bd
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==TopDesign || ORIG_REF_NAME==TopDesign} -quiet] -quiet

# IP: bd/TopDesign/ip/TopDesign_rgb2dvi_0/TopDesign_rgb2dvi_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==TopDesign_rgb2dvi_0 || ORIG_REF_NAME==TopDesign_rgb2dvi_0} -quiet] -quiet

# IP: bd/TopDesign/ip/TopDesign_v_axi4s_vid_out_0/TopDesign_v_axi4s_vid_out_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==TopDesign_v_axi4s_vid_out_0 || ORIG_REF_NAME==TopDesign_v_axi4s_vid_out_0} -quiet] -quiet

# IP: bd/TopDesign/ip/TopDesign_v_tc_0/TopDesign_v_tc_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==TopDesign_v_tc_0 || ORIG_REF_NAME==TopDesign_v_tc_0} -quiet] -quiet

# IP: bd/TopDesign/ip/TopDesign_processing_system7_0_0/TopDesign_processing_system7_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==TopDesign_processing_system7_0_0 || ORIG_REF_NAME==TopDesign_processing_system7_0_0} -quiet] -quiet

# IP: bd/TopDesign/ip/TopDesign_ps7_0_axi_periph_0/TopDesign_ps7_0_axi_periph_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==TopDesign_ps7_0_axi_periph_0 || ORIG_REF_NAME==TopDesign_ps7_0_axi_periph_0} -quiet] -quiet

# IP: bd/TopDesign/ip/TopDesign_rst_ps7_0_100M_0/TopDesign_rst_ps7_0_100M_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==TopDesign_rst_ps7_0_100M_0 || ORIG_REF_NAME==TopDesign_rst_ps7_0_100M_0} -quiet] -quiet

# IP: bd/TopDesign/ip/TopDesign_snake_output_0_0/TopDesign_snake_output_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==TopDesign_snake_output_0_0 || ORIG_REF_NAME==TopDesign_snake_output_0_0} -quiet] -quiet

# IP: bd/TopDesign/ip/TopDesign_xbar_0/TopDesign_xbar_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==TopDesign_xbar_0 || ORIG_REF_NAME==TopDesign_xbar_0} -quiet] -quiet

# IP: bd/TopDesign/ip/TopDesign_axi_gpio_0_0/TopDesign_axi_gpio_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==TopDesign_axi_gpio_0_0 || ORIG_REF_NAME==TopDesign_axi_gpio_0_0} -quiet] -quiet

# IP: bd/TopDesign/ip/TopDesign_auto_pc_0/TopDesign_auto_pc_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==TopDesign_auto_pc_0 || ORIG_REF_NAME==TopDesign_auto_pc_0} -quiet] -quiet

# XDC: bd/TopDesign/TopDesign_ooc.xdc
